# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 11:15
from __future__ import unicode_literals

import apps.lesson.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.lesson.models.lesson_upload_to, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.lesson.models.lesson_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.lesson.models.lesson_set_upload_to, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.lesson.models.lesson_set_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.lesson.models.page_upload_to, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.lesson.models.page_upload_to)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='lesson.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sets', to='lesson.LessonSet'),
        ),
    ]
