# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20170816_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default='dsf', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonset',
            name='topic',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
