# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20170816_1202'),
        ('question', '0002_answer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lesson.Lesson'),
            preserve_default=False,
        ),
    ]
