# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
