# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_useranswer_answer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255, verbose_name="Question's text"),
        ),
    ]
