# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_blockeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
